apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      {{- if .Values.NodePort.enabled }}
      nodePort: {{ .Values.NodePort.port }}
      {{- end }}
  type: {{ if .Values.NodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
