apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: "Always"
          ports:
            - containerPort: {{ .Values.api.servicePort }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.databaseURL }}"
            - name: SIGNING_SECRET
              value: "{{ .Values.api.signingSecret }}"
      restartPolicy: Always