registry: registry.vahin.dev
imagePullSecrets:
  - name: registry-secret

postgres:
  image: 
    repository: postgres
    tag: 17-alpine
  user: Aetheris
  password: Aetheris
  db: Aetheris
  replicaCount: 1  # Number of replicas for Postgres
  servicePort: 5432
  storageSize: 50Gi

api:
  image:
    repository: vahin/aetheris
    tag: latest
  replicaCount: 2  # Number of replicas for Aetheris API
  service:
    port: 8000
  environment: 
    POSTGRES_USER: Aetheris
    POSTGRES_PASSWORD: Aetheris
    POSTGRES_DB: Aetheris
  resources: {}

NodePort:
  enabled: true
  port: 30006